TYPO3:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Flownative.Neos.CacheManagement': ['Modules']

    modules:
      administration:
        submodules:
          flownativeCacheManagementCaches:
            label: 'Caches'
            icon: 'icon-bolt'
            controller: '\Flownative\Neos\CacheManagement\Controller\Module\Administration\CachesController'
            description: 'Provides administration tools for maintaining caches.'
            privilegeTarget: 'Flownative.Neos.CacheManagement:Backend.Module.Administration.Caches'
